window.noname_package={
	character:{
		// standard:'标准',
		// refresh:'界限突破',
		// shenhua:'神话再临',
		// xinghuoliaoyuan:'星火燎原',
		// yijiang:'一将成名',
		Beginner:'初心者卡包',
		hololive:'hololive',
		nijisanji:'nijisanji',
		vtuber:'企业大箱',
		clubs: '社团小箱',
		// moyu: '摸鱼',
		yuzu: '测试中可选',
		emperor:'Emperor',
		// sp:'SP',
		// extra:'神将',		
		// mobile:'移动版',
		// old:'怀旧',
		// diy:'DIY',
		// tw:'外服武将',
		// yxs:'英雄杀',
		// hearth:'炉石传说',
		// gwent:'昆特牌',
		// mtg:'万智牌',
		// ow:'守望先锋',
		// swd:'轩辕剑',
		// gujian:'古剑奇谭',
		// xianjian:'仙剑奇侠传',
	},
	card:{
		standard:'标准',
		extra:'军争',
		sp:'SP',
		yingbian:'应变篇',
		vtuber:'化鲸篇',
		guozhan:'国战',
		zhulu:'逐鹿天下',
		// zhenfa:'阵法',
		yunchou:'运筹帷幄',
		longlaoguan:'龙牢关',
		// swd:'轩辕剑',
		// gujian:'古剑奇谭',
		// hearth:'炉石传说',
		// gwent:'昆特牌',
		// mtg:'万智牌',
		// huanlekapai:'欢乐卡牌',
	},
	play:{
		boss:'诸神降临',
		cardpile:'牌堆补充',
		wuxing:'五行生克',
		coin:'富甲天下',
	},
	mode:{
		identity:'身份',
		//guozhan:'国战',
		versus:'对决',
		connect:'联机',
		boss:'挑战',
		doudizhu:'斗地主',
		longlaoguan:'龙牢关', 
		single:'单挑',
	},
	submode:{
		identity:{
			normal:'身份模式',
			zhong:'忠胆英杰',
			purple:'3v3v2',
		},
		guozhan:{
			normal:'国战模式',
			mingjiang:'明将国战'
		},
		versus:{
			four:'四人对抗',
			three:'统率三军',
			two:'欢乐成双',
			jiange:'守卫剑阁',
			siguo:'四国争霸',
			standard:'自由对决'
		},
		chess:{
			combat:'战棋模式',
			three:'战棋统率',
			leader:'战棋君主'
		},
		single:{
			normal:'新1v1',
		},
	},
	background:{
		ol_bg:'龙纹',
		zhulin_bg:'竹林',
		shengshi_bg:'盛世',
		taoyuan_bg:'桃园',
		mea_bg:'Mea',
		ch1_bg:'彩虹1',
		ch2_bg:'彩虹2',
		ch3_bg:'彩虹3',
		ch4_bg:'彩虹4',
		ch5_bg:'彩虹5',
		ch6_bg:'彩虹6',
		ch8_bg:'彩虹8',
		ch9_bg:'彩虹9',
		ch10_bg:'组合2',
		chyj_bg:'彩虹一家',
		holo1_bg:'holo1',
		holo2_bg:'holo2',
		holo3_bg:'holo3',
		holo4_bg:'holo4',
		zh1_bg:'组合1',
		tw1_bg:'天王1',
		tw2_bg:'天王2',
		tw3_bg:'天王3',
		tw4_bg:'天王4',
		ak1_bg:'阿夸1',
		ak2_bg:'阿夸2',
		ak3_bg:'阿夸3',
		ak4_bg:'阿夸4',
		xm1_bg:'熊猫人1',
		xm2_bg:'熊猫人2',
		xm3_bg:'熊猫人3',
		alice1_bg:'爱丽丝1',
		alice2_bg:'爱丽丝2',
		alice3_bg:'爱丽丝3',
		alice4_bg:'爱丽丝4',
		hb1_bg:'海报1',
		yinxiang_bg:'印象',
		wuming_bg:'无名',
	},
	music:{
		music_phliosophy:'Philosophy of ours',
		music_diaochan:'貂蝉',
		music_shezhan:'舌战群儒',
		music_danji:'千里走单骑',
		music_jifeng:'祭风',
		music_jilve:'极略',
		music_minatoAqua1:'凑阿库娅1',
	},
	font:{
		xiaozhuan:'小篆',
		xinwei:'新魏',
		huangcao:'黄草',
		yuanli:'楷体',
		xingkai:'行楷',
		shousha:'手杀',
	},
	theme:{
		woodden:'木纹',
		music:'音乐',
		simple:'简约'
	}
};
