window.vk_package={
	character:{
		// standard:'标准',
		Beginner:'初心者卡包',
		hololive:'hololive',
		nijisanji:'nijisanji',
		vtuber:'企业大箱',
		clubs: '社团小箱',
		huajing:'化鲸篇',
		xingtian:'星天篇',
		yuzu: '测试中可选',
		emperor:'Emperor',
		sololive:'特殊角色',
		// sp:'技能库',
		// extra:'神将',
		// mobile:'移动版',
	},
	card:{
		standard:'标准',
		extra:'军争',
		huajing:'化鲸篇',
		xingtian:'星天篇',
		sp:'忠胆英杰',
		guozhan:'国战',
		yingbian:'应变篇',
		zhulu:'逐鹿天下',
		// zhenfa:'阵法',
		yunchou:'运筹帷幄',
		// longlaoguan:'龙牢关',
		// remark:'回调牌堆',
	},
	play:{
		boss:'诸神降临',
		cardpile:'牌堆补充',
		wuxing:'五行生克',
		coin:'富甲天下',
	},
	mode:{
		// richer:'大富翁',
		identity:'身份',
		doudizhu:'斗地主',
		versus:'对决',
		connect:'联机',
		guozhan:'国战', 
		boss:'挑战',
		longlaoguan:'龙牢关',
		// strategy:'战略',
		brawl:'乱斗',
		single:'单挑',
		yindao:'引导',
	},
	submode:{
		identity:{
			normal:'身份模式',
			zhong:'忠胆英杰',
			purple:'3v3v2',
		},
		guozhan:{
			normal:'国战模式',
			mingjiang:'明将国战'
		},
		versus:{
			four:'四人对抗',
			three:'统率三军',
			two:'欢乐成双',
			jiange:'虹杏战场',
			siguo:'四国争霸',
			standard:'自由对决'
		},
		chess:{
			combat:'战棋模式',
			three:'战棋统率',
			leader:'战棋君主'
		},
		single:{
			normal:'新1v1',
		},
	},
	background:{
		ol_bg:'龙纹',
		zhulin_bg:'竹林',
		shengshi_bg:'盛世',
		taoyuan_bg:'桃园',
		huangtian_bg:'黄天',
		xinsha_bg:'新杀',
		guozhan1_bg:'四大势力',
		mea_bg:'Mea',
		HNST_bg:'HNST',
		ch1_bg:'彩虹1',
		ch2_bg:'彩虹2',
		ch3_bg:'彩虹3',
		chyj_bg:'彩虹一家',
		holo1_bg:'木口1',
		holo2_bg:'木口2',
		holo3_bg:'木口3',
		huajing_bg:'化鲸',
		zh1_bg:'组合1',
		zh2_bg:'组合2',
		tw1_bg:'天王1',
		tw2_bg:'天王2',
		tw3_bg:'天王3',
		ak1_bg:'阿夸1',
		ak2_bg:'阿夸2',
		ak3_bg:'阿夸3',
		ssk_bg:'笹木咲',
		alice1_bg:'爱丽丝1',
		alice2_bg:'爱丽丝2',
		hb1_bg:'海报1',
		svg_simple1_bg:'简约1',
		svg_simple2_bg:'简约2',
		svg_simple3_bg:'简约3',
	},
	music:{
		music_danji:'千里走单骑',
		music_XiandTao:'小希小桃',
		music_diana:'嘉然',
		music_minatoAqua:'凑阿库娅',
		music_usadaPekora:'兔田佩克拉',
		music_VTL:'Virtual to LIVE',
		music_Quiet:'Quiet',
		music_kaitian:'开天',
		music_phliosophy:'Philosophy of ours',
		music_shezhan:'舌战群儒',
		music_jifeng:'祭风',
		music_jilve:'极略',
	},
	font:{
		Tiejili: '铁蒺藜',
		LuoLiTi2: '萝莉',
		hyk2gj: '汉仪菱心',
		xiaozhuan:'小篆',
		xinwei:'新魏',
		huangcao:'黄草',
		yuanli:'楷体',
		xingkai:'行楷',
		shousha:'手杀',
	},
	theme:{
		vk:'VK',
		woodden:'木纹',
		music:'音乐',
		simple:'简约'
	}
};
