window.noname_update={
	version:'1.9.103.2',
	update:'1.9.101.1.1',
	changeLog:[
		'1.9.103.2小更新：新增机制：升阶（在同时开启武将包与卡牌包的《星天篇》时激活），新增势力：EgoLive，新增角色：宇佐纪诺诺、莱妮娅，修改部分描述，修复初心萝卜子『机电』的bug，调整背景分布。',
		'',
		'在菜单-其他-帮助里，增加“FAQ”栏',
		'化鲸篇新增机制可以在帮助中查看',
		'化鲸篇人物：VR的七海、神乐组的koyori、P-SP的白神遥、彩虹的长尾景和海·sasaki、HOLO的海·aqua、HOLOEN的噶呜·古拉和一伊那尔栖、asoul的海·向晚、特典的绯赤艾莉欧和噶呜·古拉',
	],
	files:[
		'image/character/Ava.jpg',
		'image/character/Carol.jpg',
		'image/character/Reine.jpg',
		'image/character/RobokoSan.jpg',
		'image/character/Xiaorou.jpg',

		'image/card/sha.png',
		'image/card/chuqibuyi.png',


		'character/Beginner.js',
		'character/hololive.js',
		'character/clubs.js',
		'character/emperor.js',
		'character/nijisanji.js',
		'character/vtuber.js',
		'character/yuzu.js',
		'character/huajing.js',
		'character/sololive.js',
		'character/xingtian.js',
		
		'card/huajing.js',
		'card/longlaoguan.js',
		'card/yingbian.js',
		'card/extra.js',
		'card/sp.js',
		'card/standard.js',
		'card/guozhan.js',
		'card/remark.js',
		// 'card/gwent.js',
		'card/yunchou.js',
		'card/zhenfa.js',
		'card/zhulu.js',
		'card/xingtian.js',
		// 'character/diy.js',
		// 'character/refresh.js',
		// 'character/shenhua.js',
		'character/sp.js',
		//'extension/boss/extension.js',
		'layout/default/layout.css',
		'layout/default/menu.css',
		// 'layout/nova/layout.css',
		'mode/identity.js',
		'mode/doudizhu.js',
		'mode/guozhan.js',
		'mode/single.js',
		'mode/brawl.js',
		'mode/longlaoguan.js',
		'mode/versus.js',
		'mode/boss.js',
		'game/game.js',
		//'game/NoSleep.js',
		//'game/config.js',
		'game/package.js',
		'game/asset.js',
		'game/source.js',
	]
};
