window.noname_update={
	version:'1.9.102.8',
	update:'1.9.100.113.6',
	changeLog:[
		'102.8小更新：修复bug，新增角色：永雏塔菲，优化了许多技能的显示，VR统一移至企业包，花谱、星宫汐、三川、樱井移出测试包。',
		'102.7小更新：修复各种bug',
		'在菜单-其他-帮助里，增加“FAQ”栏',
		'化鲸篇新增机制可以在帮助中查看',
		'化鲸篇人物：VR的七海、神乐组的koyori、P-SP的白神遥、彩虹的长尾景和海·sasaki、HOLO的海·aqua、HOLOEN的噶呜·古拉和一伊那尔栖、asoul的海·向晚、特典的绯赤艾莉欧和噶呜·古拉',
	],
	files:[
		'audio/skill/yehua1.mp3',
		'audio/skill/yehua2.mp3',
		'audio/skill/yehua3.mp3',

		'character/Beginner.js',
		'character/hololive.js',
		'character/clubs.js',
		'character/emperor.js',
		'character/nijisanji.js',
		'character/vtuber.js',
		'character/yuzu.js',
		'character/huajing.js',
		'character/sololive.js',
		
		'card/huajing.js',
		'card/longlaoguan.js',
		'card/yingbian.js',
		'card/extra.js',
		'card/sp.js',
		'card/standard.js',
		'card/guozhan.js',
		'card/remark.js',
		// 'card/gwent.js',
		'card/yunchou.js',
		'card/zhenfa.js',
		'card/zhulu.js',
		// 'character/diy.js',
		// 'character/refresh.js',
		// 'character/shenhua.js',
		'character/sp.js',
		//'extension/boss/extension.js',
		'layout/default/layout.css',
		'layout/default/menu.css',
		// 'layout/nova/layout.css',
		'mode/identity.js',
		'mode/doudizhu.js',
		'mode/guozhan.js',
		'mode/single.js',
		'mode/brawl.js',
		'mode/longlaoguan.js',
		'mode/versus.js',
		'mode/boss.js',
		'game/game.js',
		//'game/NoSleep.js',
		//'game/config.js',
		'game/package.js',
		'game/asset.js',
		'game/source.js',
	]
};
