window.noname_update={
	version:'1.9.103.14',
	update:'1.9.101.1.1',
	changeLog:[
		`1.9.103.15小更新：新增势力：网易；新增角色：栗子酱(网易)、海·星宫汐(个人势/群:化鲸包)`,
		`标准樋口枫的技能组重置，标准月之美兔增加主公技，调整初心(国战)白雪巴与健屋花那的技能效果、小柔的技能效果`,
		`千幽茉里、奈罗花、MeUmy移出测试包，修复部分bug，修改部分描述，修改神宫司玉藻『傲尾』ai`,
		``,
		``,
		`化鲸篇新增机制可以在游戏内或者设置的“帮助”中查看`,
		`化鲸篇角色：VR的七海、神乐组的koyori、P-SP的白神遥、彩虹的长尾景、HOLO的噶呜·古拉和一伊那尔栖、
		海洋特典角色（湊阿夸、笹木咲、向晚、星宫汐）、皇特典（绯赤艾莉欧、噶呜·古拉）`,
	],
	files:[
		'image/character/Nekomasu.jpg',
		'image/character/re_Nekomasu.jpg',
		'image/character/Xiaorou.jpg',

		'character/Beginner.js',
		'character/hololive.js',
		'character/clubs.js',
		'character/emperor.js',
		'character/nijisanji.js',
		'character/vtuber.js',
		'character/yuzu.js',
		'character/huajing.js',
		'character/sololive.js',
		'character/xingtian.js',
		// 'character/diy.js',
		// 'character/refresh.js',
		// 'character/shenhua.js',
		// 'character/sp.js',
		
		'card/huajing.js',
		'card/longlaoguan.js',
		'card/yingbian.js',
		'card/extra.js',
		'card/sp.js',
		'card/standard.js',
		'card/guozhan.js',
		'card/remark.js',
		// 'card/yunchou.js',
		// 'card/zhenfa.js',
		// 'card/zhulu.js',
		'card/xingtian.js',
		// 'card/gwent.js',
		//'extension/boss/extension.js',
		'layout/default/layout.css',
		'layout/default/menu.css',
		// 'layout/nova/layout.css',
		'mode/identity.js',
		'mode/doudizhu.js',
		'mode/guozhan.js',
		'mode/single.js',
		'mode/brawl.js',
		'mode/longlaoguan.js',
		'mode/versus.js',
		'mode/boss.js',
		'game/game.js',
		//'game/NoSleep.js',
		//'game/config.js',
		'game/package.js',
		'game/asset.js',
		'game/source.js',
	]
};
