declare type lib_config = {
	forbidai:string[],
	forbidai_user:string[],
	forbidall: string[],
	forbidstone:string[],
	forbidchess:string[],
	forbidboss:string[],
	forbiddouble:string[],
	forbidthreecard:string[],
	all:{
		sgscharacters:string[],
		sgscards:string,
		sgsmodes:string[],
		stockmode:string[],
		stockextension:string[],
		layout:string[],
		theme:string[],
		card_font:string[],
		double_hp:string[],
		image_background_filter:string[],
	},

	game:string,
	duration:number,
	hoveration:number,
	doubleclick_intro:true,
	cheat:false,
	volumn_background:number,
	volumn_audio:number,

	connect_avatar:string,
	connect_nickname:string,
	config_menu:true,
	auto_popped_config:true,
	auto_popped_history:false,
	auto_skill:true,
	auto_confirm:true,
	enable_drag:true,
	hover_handcard:true,
	hover_all:true,
	right_info:true,
	longpress_info:true,
	long_info:true,
	background_music:string,
	background_audio:true,
	background_speak:true,
	glow_phase:string,
	die_move:string,

	skin:Record<string, any>,
	gameRecord:Record<string, any>,
	extensionInfo:Record<string, any>,
	autoskilllist:string[],
	hiddenModePack:string[],
	hiddenCharacterPack:string[],
	hiddenCardPack:string[],
	hiddenPlayPack:string[],
	hiddenBackgroundPack:string[],
	customBackgroundPack:string[],
	favouriteCharacter:string[],
	favouriteMode:string[],
	recentIP:string[],
	vintageSkills:string[],
	alteredSkills:string[],
	brokenFile:string[],

	theme:string,
	layout:string,
	card_style:string,
	cardback_style:string,
	hp_style:string,

	image_character:string,
	image_background:string,

	asset_image:true,
	asset_font:true,

	replace_image:false,

	card_font:string,
	show_statusbar_ios:string,
	show_statusbar_android:false,
	show_name:true,
	show_replay:false,
	show_round_menu:true,
	show_pause:true,
	show_auto:true,
	show_volumn:true,
	show_cardpile:true,
	only_fullskin:true,
	show_connect:true,
	show_wuxie:false,
	show_wuxie_self:true,
	show_stat:true,
	show_playerids:true,
	show_scrollbar:false,
	mousewheel:true,
	fold_card:true,
	threed_card:false,
	vertical_scroll:false,
	handcard_scroll:number,
	animation:true,
	skill_animation_type:string,
	paused:false,
	title:false,
	button_press:true,
	damage_shake:true,
	log_highlight:true,
	player_border:string,
	radius_size:string,

	modeconfig:false,
	gameconfig:false,
	appearence:false,
	video:string,
	coin:number,

	intro:string,
	right_click:string,
	sort:string,

	cards:string[],
	characters:string[],
	connect_characters:string[],
	connect_cards:string[],
	plays:string[],
	extensions:string[],
	banned:string[],
	bannedcards:string[],
	forbidlist:string[],
	bannedpile:Record<string, any>,
	customcardpile:Record<string, any>,
	addedpile:Record<string, any>,

	mode:string,
	mode_config:{
		global:{
			player_number:number,
			auto_identity:string,
			double_character:false,
			save_progress:true,
			free_choose:true,
			swap:true,
			change_identity:true,
			battle_number:number,
			double_hp:string,
		},
		identity:{
			identity:string[][],
			choice:{
				zhu:number,
				zhong:number,
				nei:number,
				fan:number,
			},
			show_identity:true,
			difficulty:string,
			dierestart:true
		},
		guozhan:{
			difficulty:string,
			initshow_draw:string,
			dierestart:true
		},
        [modeName: string]: Record<string, any>
	},
	current_mode:Record<string, any>,
	customforbid:string[],
	forbid:[string, string][],
    [prop:string]:any
};
